<?php

/**
 * Autogenerated base class for the Places model.
 * 
 * Don't change this file, since it can be overwritten.
 * Instead, change the Places.php file.
 *
 * @module Places
 */
/**
 * Base class for the Places model
 * @class Base_Places
 */
abstract class Base_Places
{
	/**
	 * The list of model classes
	 * @property $table_classnames
	 * @type array
	 */
	static $table_classnames = array (
  0 => 'Places_Autocomplete',
  1 => 'Places_City',
  2 => 'Places_Country',
  3 => 'Places_District',
  4 => 'Places_Hierarchy',
  5 => 'Places_Ipv4',
  6 => 'Places_Ipv6',
  7 => 'Places_Location',
  8 => 'Places_Postcode',
  9 => 'Places_Region',
);

	/**
     * This method calls Db.connect() using information stored in the configuration.
     * If this has already been called, then the same db object is returned.
	 * @method db
	 * @return {Db_Interface} The database object
	 */
	static function db()
	{
		return Db::connect('Places');
	}

	/**
	 * The connection name for the class
	 * @method connectionName
	 * @return {string} The name of the connection
	 */
	static function connectionName()
	{
		return 'Places';
	}
};